import { TRIP_STATUS, WEATHER_ICONS } from "@/constants/trips";

const COVERS = {
  paris:
    "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
  tokyo:
    "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
  newYork:
    "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80",
  bali: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
  rome: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80",
};

function doneActivity(id, title, location, date, time, category) {
  return {
    id,
    title,
    location,
    date,
    time,
    category,
    priority: "Medium",
    status: "Done",
  };
}

export const additionalTrips = {
  trip_002: {
    tripId: "trip_002",
    tripName: "Paris Romance & Arts",
    tripType: "Couple",
    destination: "Paris, France",
    country: "France",
    startDate: "2026-07-05",
    endDate: "2026-07-12",
    status: TRIP_STATUS.ACTIVE,
    currency: "EUR",
    budget: 4500,
    coverImage: COVERS.paris,
    weatherIcon: WEATHER_ICONS.CLOUDY,
    description: "Museums, cafés, and evening walks along the Seine.",
    itinerary: [
      doneActivity(
        1,
        "Arrival at CDG",
        "Charles de Gaulle Airport",
        "2026-07-05",
        "10:00",
        "Transport",
      ),
      {
        id: 2,
        title: "Louvre Museum",
        location: "Rue de Rivoli",
        date: "2026-07-06",
        time: "09:30",
        category: "Sightseeing",
        priority: "High",
        status: "Planned",
      },
      {
        id: 3,
        title: "Eiffel Tower Sunset",
        location: "Champ de Mars",
        date: "2026-07-07",
        time: "19:00",
        category: "Sightseeing",
        priority: "Medium",
        status: "Planned",
      },
      {
        id: 4,
        title: "Montmartre Dinner",
        location: "Montmartre",
        date: "2026-07-08",
        time: "20:00",
        category: "Food",
        priority: "Low",
        status: "Planned",
      },
    ],
    packingList: [
      {
        id: 1,
        name: "Passport",
        category: "Documents",
        quantity: 2,
        required: "Yes",
        packed: "Yes",
      },
      {
        id: 2,
        name: "Light Jacket",
        category: "Clothes",
        quantity: 2,
        required: "Yes",
        packed: "No",
      },
    ],
    budgetItems: [
      {
        id: 1,
        name: "Flights",
        category: "Transport",
        estimatedCost: 1800,
        actualCost: 1750,
        paymentStatus: "Paid",
      },
      {
        id: 2,
        name: "Boutique Hotel",
        category: "Accommodation",
        estimatedCost: 2000,
        actualCost: 0,
        paymentStatus: "Unpaid",
      },
    ],
    meta: {
      createdAt: "2026-01-10T00:00:00Z",
      lastUpdated: "2026-05-10T00:00:00Z",
    },
  },

  trip_003: {
    tripId: "trip_003",
    tripName: "Tokyo Street Food",
    tripType: "Solo",
    destination: "Tokyo, Japan",
    country: "Japan",
    startDate: "2025-09-14",
    endDate: "2025-09-21",
    status: TRIP_STATUS.PAST,
    currency: "JPY",
    budget: 320000,
    coverImage: COVERS.tokyo,
    weatherIcon: WEATHER_ICONS.RAINY,
    description: "",
    itinerary: [
      doneActivity(
        1,
        "Ramen Tour Shinjuku",
        "Shinjuku",
        "2025-09-15",
        "18:00",
        "Food",
      ),
      doneActivity(
        2,
        "Tsukiji Outer Market",
        "Tsukiji",
        "2025-09-16",
        "08:00",
        "Food",
      ),
    ],
    packingList: [
      {
        id: 1,
        name: "JR Pass printout",
        category: "Documents",
        quantity: 1,
        required: "Yes",
        packed: "Yes",
      },
    ],
    budgetItems: [
      {
        id: 1,
        name: "Food tours",
        category: "Food",
        estimatedCost: 80000,
        actualCost: 75000,
        paymentStatus: "Paid",
      },
    ],
    meta: {
      createdAt: "2025-06-01T00:00:00Z",
      lastUpdated: "2025-10-01T00:00:00Z",
    },
  },

  trip_004: {
    tripId: "trip_004",
    tripName: "New York Tech Summit",
    tripType: "Business",
    destination: "New York, USA",
    country: "USA",
    startDate: "2025-10-02",
    endDate: "2025-10-05",
    status: TRIP_STATUS.PAST,
    currency: "USD",
    budget: 5000,
    coverImage: COVERS.newYork,
    weatherIcon: WEATHER_ICONS.SUNNY,
    description: "",
    itinerary: [
      doneActivity(
        1,
        "Conference Keynote",
        "Javits Center",
        "2025-10-03",
        "09:00",
        "Other",
      ),
    ],
    packingList: [],
    budgetItems: [
      {
        id: 1,
        name: "Conference ticket",
        category: "Activity",
        estimatedCost: 1200,
        actualCost: 1200,
        paymentStatus: "Paid",
      },
    ],
    meta: {
      createdAt: "2025-07-15T00:00:00Z",
      lastUpdated: "2025-10-06T00:00:00Z",
    },
  },

  trip_005: {
    tripId: "trip_005",
    tripName: "Bali Wellness Retreat",
    tripType: "Wellness",
    destination: "Ubud, Indonesia",
    country: "Indonesia",
    startDate: "2025-11-15",
    endDate: "2025-11-25",
    status: TRIP_STATUS.PAST,
    currency: "USD",
    budget: 2800,
    coverImage: COVERS.bali,
    weatherIcon: WEATHER_ICONS.SUNNY,
    description: "",
    itinerary: [
      doneActivity(
        1,
        "Yoga at Sunrise",
        "Ubud Rice Terraces",
        "2025-11-16",
        "06:00",
        "Activity",
      ),
    ],
    packingList: [
      {
        id: 1,
        name: "Yoga Mat",
        category: "Personal",
        quantity: 1,
        required: "No",
        packed: "Yes",
      },
    ],
    budgetItems: [],
    meta: {
      createdAt: "2025-08-01T00:00:00Z",
      lastUpdated: "2025-11-26T00:00:00Z",
    },
  },

  trip_006: {
    tripId: "trip_006",
    tripName: "Rome History Walk",
    tripType: "Culture",
    destination: "Rome, Italy",
    country: "Italy",
    startDate: "2025-12-10",
    endDate: "2025-12-17",
    status: TRIP_STATUS.PAST,
    currency: "EUR",
    budget: 3600,
    coverImage: COVERS.rome,
    weatherIcon: WEATHER_ICONS.CLOUDY,
    description: "",
    itinerary: [
      doneActivity(
        1,
        "Colosseum Tour",
        "Piazza del Colosseo",
        "2025-12-11",
        "10:00",
        "Sightseeing",
      ),
      doneActivity(
        2,
        "Vatican Museums",
        "Vatican City",
        "2025-12-12",
        "09:00",
        "Sightseeing",
      ),
    ],
    packingList: [],
    budgetItems: [
      {
        id: 1,
        name: "Museum passes",
        category: "Activity",
        estimatedCost: 120,
        actualCost: 120,
        paymentStatus: "Paid",
      },
    ],
    meta: {
      createdAt: "2025-09-01T00:00:00Z",
      lastUpdated: "2025-12-18T00:00:00Z",
    },
  },
};
