export const packingList = [
  {
    id: 1,
    name: "Vietnam Visa / E-visa Copy",
    category: "Documents",
    quantity: 1,
    requiredStatus: "Required",
    packedStatus: "Not Packed",
  },
  {
    id: 2,
    name: "Universal Travel Adapter",
    category: "Electronics",
    quantity: 1,
    requiredStatus: "Required",
    packedStatus: "Packed",
  },
  {
    id: 3,
    name: "Light Rain Jacket",
    category: "Clothes",
    quantity: 1,
    requiredStatus: "Required",
    packedStatus: "Not Packed",
  },
  {
    id: 4,
    name: "Comfortable Walking Shoes",
    category: "Clothes",
    quantity: 1,
    requiredStatus: "Required",
    packedStatus: "Packed",
  },
  {
    id: 5,
    name: "Power Bank (20,000mAh)",
    category: "Electronics",
    quantity: 1,
    requiredStatus: "Optional",
    packedStatus: "Not Packed",
  },
  {
    id: 6,
    name: "Motion Sickness Tablets",
    category: "Medicine",
    quantity: 1,
    requiredStatus: "Required",
    packedStatus: "Not Packed",
  },
  {
    id: 7,
    name: "Sunscreen (SPF 50+)",
    category: "Personal",
    quantity: 1,
    requiredStatus: "Optional",
    packedStatus: "Not Packed",
  },
  {
    id: 8,
    name: "Hanoi Street Food Guide (Print)",
    category: "Other",
    quantity: 1,
    requiredStatus: "Optional",
    packedStatus: "Not Packed",
  },
  {
    id: 9,
    name: "Linen Shirts",
    category: "Clothes",
    quantity: 2,
    requiredStatus: "Optional",
    packedStatus: "Not Packed",
  },
  {
    id: 10,
    name: "Passport & Copies",
    category: "Documents",
    quantity: 2,
    requiredStatus: "Required",
    packedStatus: "Packed",
  },
  {
    id: 11,
    name: "Passport & Copies",
    category: "Documents",
    quantity: 2,
    requiredStatus: "Required",
    packedStatus: "Packed",
  },
];
